version: 1
builder:
  configs:
  - platform: linux
    swift_version: '6.1'
    image: registry.gitlab.com/finestructure/spi-images:basic-6.1-latest
  - platform: linux
    swift_version: '6.0'
    image: registry.gitlab.com/finestructure/spi-images:basic-6.0-latest
  - platform: linux
    swift_version: '5.10'
    image: registry.gitlab.com/finestructure/spi-images:basic-5.10-latest
  - platform: linux
    swift_version: '5.9'
    image: registry.gitlab.com/finestructure/spi-images:basic-5.9-latest
