disabled_rules:
  - type_name
  - identifier_name
  - force_cast
  - switch_case_alignment

line_length: 140

included:
  - Sources
excluded:
  - Sources/SwiftCrossUI/ViewGraph/ViewGraphNodeChildren.swift
  - Sources/SwiftCrossUI/Builders/ViewContentBuilder.swift
  - Sources/SwiftCrossUI/Views/ViewContent.swift
